### ISSUE TITLE
Do Elk Hills wells from Big Kids' geochem table

### ISSUE THREAD

**Issue by whdc** [sac-water/neuralog#7]
There are 167 wells for Elk Hills in the Big Kids' geochem table. Have people go thru them, and neuralog those with:
  • deep resistivity
  • shallow resistivity
  • gamma-gamma density or porosity
  • nphi
  • SP
The API numbers are [here](https://github.com/sac-water/neuralog/files/572347/elk-hills.txt).

**Comment by michaeljstephens21** [comment]
Assigned to Jenaro (I added ten) total of 177.

**Comment by michaeljstephens21** [comment]
02929213 and 02929199 have all five and are digitized. 02929021 porosity starts at 6500 ft.
[dropbox link here](https://www.dropbox.com/sh/7wqo2l29x1uoq7n/AAAYNm-iRgWfYgmQdfnqnomQa?dl=0)
